### ISSUE TITLE
Improve config parsing + General module API improvements

### ISSUE THREAD

**Issue by MDFL64** [glua/gm_voxelate#6]
- [x] Make exterior mesh generation option shared (Serverside physical mesh garbage probably wants to know whether it should generate external faces.)
- [x] Just read everything regardless of state.
- [x] Make bounds in voxels, not chunks? Add option for huge worlds?
- [x] Move generator func into config, there's no reason this re-init logic should be necessary. (Partly done, but not well.)
- [x] Require system init to have a config. This removes the two step process and a lot of fuckuppery.
- [x] Just stick the config struct inside voxelworld instead of using a stoopid pointer.
- [x] Remove all the shit dealing with checking if we're allowed to render/generate. Remove code that allows us to re-flag everything.
- [x] Remove getdata, remove data from chunk init, probably remove chunk init all together?
- [x] Add mesh generation logic consistent with bounds in blocks.
- [x] Actually make shit work on the lua side.
- [x] Call VoxelWorld:_initMisc directly. (Done on server, not done on client.)
- [x] Call generator on chunk init.

**Comment by MDFL64** [comment]
Removing:
- voxEnableMeshGeneration = luaf_voxEnableMeshGeneration = VoxelWorld::enableUpdates
- voxFlagAllChunksForUpdate = luaf_voxFlagAllChunksForUpdate = VoxelWorld::flagAllChunksForUpdate
- voxGetAllChunks = luaf_getAllChunks = **KEEP:** VoxelWorld::getAllChunkPositions()

**Comment by MDFL64** [comment]
voxReInit (lua) is also gone.

Replace:
- voxNew(index) = luaf_voxNew
- voxInit(index, config) = luaf_voxInit (Currently handles all config garbage.)

With:
- voxNewWorld(config, index?) = luaf_voxNewWorld = a lot of changes to VoxelWorld

Renamed [luaf_]voxDelete => [luaf_]voxDeleteWorld

**Comment by birdbrainswagtrain** [comment]
Doing heavy preprocessor abuse to parse configs now.

**Comment by birdbrainswagtrain** [comment]
**Todo:** Remove getdata, remove data from chunk init, probably remove chunk init all together?

**Comment by MDFL64** [comment]
- Remove Voxelate:AddVoxelWorld (lua)

**Comment by MDFL64** [comment]
Remove:
- luaf_voxData
- luaf_voxInitChunk

Leave generation shit as is since Swad's working on it.

**Comment by SwadicalRag** [comment]
you can fuck with generation now
all i did was port it to c++

**Comment by SwadicalRag** [comment]
- add parameter to disable source engine vphysics mesh generation
 - the same parameter should enable reactphysics mesh generation

**Comment by MDFL64** [comment]
Already have one for vphys, although it may be broken. Might add a second for react, not sure how to handle most of the crazy huge world shit.

**Comment by SwadicalRag** [comment]
reactphysics uses doubles, it should be able to handle the huge scale of our world

1 reactphysics unit = 1 block

**Comment by SwadicalRag** [comment]
See the #3 for discussion

**Comment by SwadicalRag** [comment]
we only load chunks that players are near into the reactphysics engine

**Comment by MDFL64** [comment]
Yeah affirmative. I wasn't questioning using react for huge worlds, seems like a physics engine is the easiest thing to do. Might just change the bool parameter to a string to specify what engine to build meshes for, I thonk it defaults to none.

**Comment by SwadicalRag** [comment]
wouldn't it be taxing to do `strcmp` each frame or when we rebuild chunks?

why are we not using a bool? it's not like we're planning to support more engines :v

**Comment by MDFL64** [comment]
It would be either a bool or enum module side. I'm talking Lua-API side.

**Comment by SwadicalRag** [comment]
oh no of course I support that 👍
